### ISSUE TITLE
pr_title includes commits:

### ISSUE THREAD

**Issue by DomVinyard** [8BitJonny/gh-get-current-pr#15]
I am using this in conjunction with rtCamp/action-slack-notify@v2 and the PR title is showing all of the commits: 

<img width="393" alt="image" src="https://user-images.githubusercontent.com/1271197/119636755-dbb6b000-be0c-11eb-93ba-4b9f7f6eb5a4.png">

When a user merges the pr, the commits are automatically included. Can they be removed or should I handle this manually

**Comment by 8BitJonny** [comment]
Huh, interesting 🤔 
My first thought is, that upon merging, all commits are included in the body of a commit. You don't often see it but every commit has a title and a body message. I'm not sure how to best tackle this in this repo, but one idea would be to look into how this PR commit is constructed.

This only happens after the PR is merged, right? If you log the PR Title with this action while the PR is still open, the commit messages should not appear. Can you confirm that?

**Comment by 8BitJonny** [comment]
And sorry for my late response. I just noticed, that I didn't had notifications enabled for this repo yet. They are enabled now, so my future responses should be quicker 👍🏼

**Comment by DomVinyard** [comment]
Yes, happy to try while the PR is still open, I will report back, but yes - it's upon merging: The Github interface gives us two fields:

<img width="842" alt="image" src="https://user-images.githubusercontent.com/1271197/120552580-55433500-c3ef-11eb-989c-9305e96160cc.png">

But with a squash merge these are just smooshed together into a single commit message. The title just becomes the first line of the description. 

I tried to use a newline split action

```
    - uses: rishabhgupta/split-by@v1
        id: split
        with:
          string: ${{ steps.PR.outputs.pr_title }}
          split-by: '\n'
```

but it's not working sadly

**Comment by 8BitJonny** [comment]
Then as a temporary solution you may have to go into the description of the Squash Merge Commit and delete the whole description. That should do the trick for now

**Comment by 8BitJonny** [comment]
>Then as a temporary solution you may have to go into the description of the Squash Merge Commit and delete the whole description. That should do the trick for now

Did this work for you?

**Comment by 8BitJonny** [comment]
closing this because of no issue activity
