### ISSUE TITLE
The `set-output` command is deprecated

### ISSUE THREAD

**Issue by IvekSRC** [8BitJonny/gh-get-current-pr#172]
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by 8BitJonny** [comment]
Thanks for pointing that out 🙏🏼 
Fixed by #157

A new release will follow shortly

**Comment by 8BitJonny** [comment]
Released in [v2.1.3](https://github.com/8BitJonny/gh-get-current-pr/releases/tag/v2.1.3)
