### ISSUE TITLE
Small refactor - Remove v from v2.1.3

### ISSUE THREAD

**Issue by IvekSRC** [8BitJonny/gh-get-current-pr#173]
I think you forgot to remove v from v2.1.3. 

![image](https://user-images.githubusercontent.com/77816097/198262728-3c701089-5e77-4ee9-8c7c-4278ae0e333e.png)

**Comment by 8BitJonny** [comment]
Thanks for the quick catch 🙏🏼  I edited the release 2.1.3 to point to the new tag `2.1.3` with out the prefix
