### ISSUE TITLE
ci: failure on comment

### ISSUE THREAD

**Issue by dargmuesli** [8BitJonny/gh-get-current-pr#292]
## Subject of the issue
When I comment on an issue, a ci run starts and fails.

## Your git environment
n/a

## Steps to reproduce
See this log: https://github.com/8BitJonny/gh-get-current-pr/actions/runs/6537248706

## Expected behaviour
I can comment without being notified about a build failure.

## Actual behaviour
I'm notified about a build failure.

**Comment by 8BitJonny** [comment]
yeah, I still had a WIP workflow lying around where I thought it would nice to be triggered by comment. Changed the trigger to manual so that no issue comments will trigger it anymore. Thanks for the headsup, wasnt aware of this
