### ISSUE TITLE
Update to nodejs 20 (16 deprecated)

### ISSUE THREAD

**Issue by jrunestone** [8BitJonny/gh-get-current-pr#294]
## Subject of the issue
GitHub urges all actions to update nodejs to 20

I'm putting this up here for now, can probably submit a pr in a while..:P

**Comment by 8BitJonny** [comment]
Released and available under v3.0.0
Thanks for the headsup @jrunestone @TWiStErRob

**Comment by TWiStErRob** [comment]
Thanks for the quick action!
